<?php

namespace App\Services;

use App\Models\AgentDocument;
use App\Models\AgentDocumentChunk;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Smalot\PdfParser\Parser as PdfParser;

class DocumentChunkService
{
    /**
     * Default chunk size (characters). ~500 chars ≈ ~125 tokens.
     */
    private const CHUNK_SIZE = 500;
    private const CHUNK_OVERLAP = 50;

    /**
     * Process an uploaded document: store file → extract text → chunk → save.
     */
    public function processDocument(AgentDocument $document): void
    {
        try {
            $document->update(['status' => 'processing']);

            // Extract text from file
            $text = $this->extractText($document);

            if (empty(trim($text))) {
                $document->update([
                    'status'        => 'failed',
                    'error_message' => 'Tidak bisa mengekstrak teks dari file.',
                ]);
                return;
            }

            // Chunk the text
            $chunks = $this->chunkText($text);

            // Delete old chunks (for re-processing)
            $document->chunks()->delete();

            // Store chunks — search_vector auto-generated by PostgreSQL trigger
            foreach ($chunks as $index => $chunk) {
                AgentDocumentChunk::create([
                    'agent_document_id' => $document->id,
                    'content'           => $chunk,
                    'chunk_index'       => $index,
                ]);
            }

            $document->update([
                'status'      => 'completed',
                'chunk_count' => count($chunks),
                'error_message' => null,
            ]);
        } catch (\Exception $e) {
            $document->update([
                'status'        => 'failed',
                'error_message' => 'Error: ' . $e->getMessage(),
            ]);
        }
    }

    /**
     * Upload and create document record.
     */
    public function uploadDocument(int $agentId, UploadedFile $file): AgentDocument
    {
        $path = $file->store("agents/{$agentId}/documents", 'local');

        return AgentDocument::create([
            'agent_id'  => $agentId,
            'filename'  => $file->getClientOriginalName(),
            'file_path' => $path,
            'file_size' => $file->getSize(),
            'mime_type' => $file->getClientMimeType(),
            'status'    => 'pending',
        ]);
    }

    /**
     * Extract text from document based on mime type.
     */
    private function extractText(AgentDocument $document): string
    {
        $fullPath = Storage::disk('local')->path($document->file_path);

        return match ($document->mime_type) {
            'application/pdf'   => $this->extractFromPdf($fullPath),
            'text/plain'        => file_get_contents($fullPath),
            'text/markdown'     => file_get_contents($fullPath),
            'text/csv'          => file_get_contents($fullPath),
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                                => $this->extractFromDocx($fullPath),
            default             => file_get_contents($fullPath),
        };
    }

    /**
     * Extract text from PDF using smalot/pdfparser.
     */
    private function extractFromPdf(string $path): string
    {
        $parser = new PdfParser();
        $pdf = $parser->parseFile($path);
        return $pdf->getText();
    }

    /**
     * Extract text from DOCX.
     */
    private function extractFromDocx(string $path): string
    {
        $zip = new \ZipArchive();
        if ($zip->open($path) !== true) {
            return '';
        }

        $content = $zip->getFromName('word/document.xml');
        $zip->close();

        if (!$content) return '';

        // Strip XML tags, keep text
        $text = strip_tags($content);
        return preg_replace('/\s+/', ' ', $text);
    }

    /**
     * Split text into chunks with overlap.
     */
    private function chunkText(string $text): array
    {
        // Clean up whitespace
        $text = preg_replace('/\s+/', ' ', trim($text));

        $chunks = [];
        $length = mb_strlen($text);
        $start = 0;

        while ($start < $length) {
            $chunk = mb_substr($text, $start, self::CHUNK_SIZE);

            // Try to end at sentence boundary
            if ($start + self::CHUNK_SIZE < $length) {
                $lastDot = mb_strrpos($chunk, '.');
                $lastNewline = mb_strrpos($chunk, "\n");
                $breakPos = max($lastDot, $lastNewline);

                if ($breakPos !== false && $breakPos > self::CHUNK_SIZE * 0.5) {
                    $chunk = mb_substr($chunk, 0, $breakPos + 1);
                }
            }

            $chunks[] = trim($chunk);
            $start += mb_strlen($chunk) - self::CHUNK_OVERLAP;

            // Avoid infinite loop on very short text
            if (mb_strlen($chunk) <= self::CHUNK_OVERLAP) break;
        }

        return array_filter($chunks, fn ($c) => mb_strlen($c) > 20);
    }
}